// If you loose one of these will be played
// Set blank to disable
LOSS_SOUNDS = {
	"vo/announcer_failure.wav",
	"vo/announcer_you_failed.wav"
}


// Sound files hunters can taunt with
// You need at least 2 files listed here
HUNTER_TAUNTS = {
	{"taunts/hunters/h1-1.mp3", "I will look for you", "7", true},
	{"taunts/hunters/h1-2.mp3", "Watching you", "5", true},
	{"taunts/hunters/h6.mp3", "I see you", "4", true},
	{"taunts/hunters/h68.mp3", "Here's Johnny!", "2", true},
	{"taunts/hunters/h1-3.mp3", "Cut your heart out", "4", true},
	{"taunts/hunters/h1-4.mp3", "Come quietly", "3", true},
	{"taunts/hunters/h1-5.mp3", "Smash your face", "9", true},
	{"taunts/hunters/h1-6.mp3", "Smash the life out of you", "6", true},
	{"taunts/hunters/h1-7.mp3", "You're in my domain now", "2", true},
	{"taunts/hunters/h1-8.mp3", "MGS Alert", "2", true},
	{"taunts/hunters/h1-9.mp3", "Attack on titan", "2", true},
	{"taunts/hunters/h1-12.mp3", "Forgot to shoot something", "2", true},
	{"taunts/hunters/h1-13.mp3", "Favourite waste of bullets", "3", true},
	{"taunts/hunters/h1-14.mp3", "I can smell you", "2", true},
	{"taunts/hunters/h1-15.mp3", "I expect you to die", "5", true},
	{"taunts/hunters/h1-16.mp3", "I see dead people", "4", true},
	{"taunts/hunters/h1-18.mp3", "Ready or not", "7", true},
	{"taunts/hunters/h1-20.mp3", "You lose", "4", true},
	{"taunts/hunters/h1-21.mp3", "Come out, come out", "3", true},
	{"taunts/hunters/h1-22.mp3", "Beaten by a little girl, ha!", "3", true},
	{"taunts/hunters/h1-23.mp3", "Come out, come out (Annie)", "4", true},
	{"taunts/hunters/h1-24.mp3", "Didn't even effing see you", "8", true},
	{"taunts/hunters/h1-26.mp3", "Feck off cup!", "2", true},
	{"taunts/hunters/h1-27.mp3", "Hunting wabbits", "5", true},
	{"taunts/hunters/h1-28.mp3", "I AM THE LAW!", "2", true},
	{"taunts/hunters/h1-29.mp3", "Assuming direct control", "4", true},
	{"taunts/hunters/h1-30.mp3", "Preparing to dispense", "4", true},
	{"taunts/hunters/h1-31.mp3", "Hello, friend", "4", true},
	{"taunts/hunters/h1-32.mp3", "There you are", "2", true},
	{"taunts/hunters/h1-33.mp3", "I see you", "2", true},
	{"taunts/hunters/h1-34.mp3", "Is anyone there?", "4", true},
	{"taunts/hunters/h1-35.mp3", "Would you come over here?", "4", true},
	{"taunts/hunters/h1-36.mp3", "These aren't the droids", "2", true},
	{"taunts/hunters/h1-37.mp3", "Hasta la vista", "4", true},
	{"taunts/hunters/h1-38.mp3", "Silence!", "2", true},
	{"taunts/hunters/h1-39.mp3", "I am the one who knocks", "2", true},
	{"taunts/hunters/h1-40.mp3", "Sound of da police", "3", true},
	{"taunts/hunters/h1-41.mp3", "Short term memory", "4", true},
	{"taunts/hunters/h1-42.mp3", "Exterminate", "2", true},
	{"taunts/hunters/h1-43.mp3", "If I ever see you here again", "6", true},
	{"taunts/hunters/h1-44.mp3", "Only supposed to blow the doors", "5", true},
	{"taunts/hunters/h1-45.mp3", "Kit Kat", "6", true},
	{"taunts/hunters/h1-46.mp3", "Let the games begin", "8", true},
	{"taunts/hunters/h1-47.mp3", "Police radio", "6", true},
	{"taunts/hunters/h1-48.mp3", "Say something", "4", true},
	{"taunts/hunters/h1-49.mp3", "Swiggity Swooty", "7", true},
	{"taunts/hunters/h1-50.mp3", "Another one bites the dust", "4", true},
	{"taunts/hunters/h1-51.mp3", "Clever one", "3", true},
	{"taunts/hunters/h1-52.mp3", "Small gun", "6", true},
	{"taunts/hunters/h1-53.mp3", "Taste your mortality", "2", true},
	{"taunts/hunters/h1-54.mp3", "That's it!", "2", true},
	{"taunts/hunters/h1-55.mp3", "The end is at hand", "2", true},
	{"taunts/hunters/h1-56.mp3", "Your last moments", "2", true},
	{"taunts/hunters/h1-57.mp3", "You deserve worse", "5", true},
}


// Sound files props can taunt with
// You need at least 2 files listed here
--  {"File path", "Name", "LengthInSeconds", ShowInTauntMenu<True/False>}
PROP_TAUNTS = {

	{"taunts/props/6.mp3", "Over 9000!", "7", true},
	{"taunts/props/14.mp3", "WRRYYYY!!!", "3", true},
	{"taunts/props/42.mp3", "Nein!", "4", true},
	{"taunts/props/44.mp3", "Huhuehue", "14", true},
	{"taunts/props/54.mp3", "I'm Slim Shady", "9", false},
	{"taunts/props/61.mp3", "Are you ready to $&%#", "5", true},
	{"taunts/props/62.mp3", "Surprise mutha' fucker", "2", true},
	{"taunts/props/63.mp3", "Friday!", "15", true},
	{"taunts/props/64.mp3", "Trolololo", "10", true},
	{"taunts/props/65.mp3", "In my butt", "8", false},
	{"taunts/props/69.mp3", "What is love", "31", true},
	{"taunts/props/70.mp3", "Scatman", "16", true},
	{"taunts/props/72.mp3", "Boom boom boom boom!", "14", false},
	{"taunts/props/75.mp3", "Somebody's watching me", "14", true},
	{"taunts/props/77.mp3", "You spin me right round", "23", false},
	{"taunts/props/78.mp3", "YMCA", "18", true},
	{"taunts/props/81.mp3", "I think he just shit himself", "15", true},
	{"taunts/props/87a.mp3", "Darude - Sandstorm", "7", true},
	{"taunts/props/90.mp3", "Now you see me", "3", false},
	{"taunts/props/91.mp3", "Wait, here I am", "3", false},
	{"taunts/props/92.mp3", "I'm here in the shadows", "3", false},
	{"taunts/props/93.mp3", "Good thing I'm indestructible", "3", true},
	{"taunts/props/97.mp3", "You're gonna love my nuts", "2", true},
	{"taunts/props/99.mp3", "I am a flaming Moltres!", "6", false},
	{"taunts/props/100.mp3", "HEYYEYAAEYAAAEYAEYAA", "13", true},
	{"taunts/props/102.mp3", "Buzz, look, an alien!", "7", true},
	{"taunts/props/105.mp3", "Banana phone!", "3", true},
	{"taunts/props/106.mp3", "Barrel roll song", "13", true},
	{"taunts/props/batman.mp3", "Spastic Batman", "9", false},
	{"taunts/props/bennyhilltheme-yaketysax.mp3", "Yakety Sax (long)", "61", false},
	{"taunts/props/countdown.mp3", "Countdown theme", "30", true},
	{"taunts/props/1-2.mp3", "Doh!", "1", true},
	{"taunts/props/1-3.mp3", "Go away", "3", false},
	{"taunts/props/1-4.mp3", "Balls of steel", "2", true},
	{"taunts/props/1-6.mp3", "Get hyper", "12", true},
	{"taunts/props/1-7.mp3", "LEEEROYYY!!!", "4", true},
	{"taunts/props/1-8.mp3", "Please come again", "2", true},
	{"taunts/props/1-9.mp3", "This is Sparta!", "3", true},
	{"taunts/props/1-10.mp3", "What is wrong with you?", "2", true},
	{"taunts/props/1-11.mp3", "Woohoo!", "2", true},
	{"taunts/props/1-12.mp3", "What do you like to play?", "4", false},
	{"taunts/props/1-14.mp3", "Stayin' alive", "24", true},
	{"taunts/props/1-15.mp3", "Snooping as usual", "3", false},
	{"taunts/props/1-16.mp3", "Atatatatatatatata", "20", false},
	{"taunts/props/1-18.mp3", "Fresh prince of Bel Air", "9", true},
	{"taunts/props/1-20.mp3", "Yakety Sax", "15", true},
	{"taunts/props/1-21.mp3", "Beverly Hills", "7", false},
	{"taunts/props/1-23.mp3", "Boom! Headshot!", "2", true},
	{"taunts/props/1-26.mp3", "Can't touch this", "12", true},
	{"taunts/props/1-27.mp3", "Careless whisper", "13", true},
	{"taunts/props/1-28.mp3", "Carl, that kills people", "2", true},
	{"taunts/props/1-36.mp3", "20th Century Fox", "20", false},
	{"taunts/props/1-37.mp3", "Charrrliieeee", "10", true},
	{"taunts/props/1-38.mp3", "Circus music", "13", false},
	{"taunts/props/1-39.mp3", "Circus afro", "8", true},
	{"taunts/props/1-40.mp3", "Crickets", "5", false},
	{"taunts/props/1-42.mp3", "Do a barrel roll!", "2", true},
	{"taunts/props/1-43.mp3", "Dun dun duuunnn", "4", false},
	{"taunts/props/1-44.mp3", "Never gonna give you up", "17", false},
	{"taunts/props/1-45.mp3", "Epic sax", "7", true},
	{"taunts/props/1-49.mp3", "Fus Ro DAh!", "2", true},
	{"taunts/props/1-50.mp3", "Hah! Gaaaayyyyyyy!", "2", true},
	{"taunts/props/1-51.mp3", "Gamecube", "5", false},
	{"taunts/props/1-52.mp3", "Gangnam style", "16", false},
	{"taunts/props/1-56.mp3", "Guile's theme", "12", true},
	{"taunts/props/1-57.mp3", "Hakuna matata", "50", false},
	{"taunts/props/1-58.mp3", "Hodor", "5", true},
	{"taunts/props/1-59.mp3", "Holy shit!", "3", true},
	{"taunts/props/1-60.mp3", "You shall not pass!", "5", true},
	{"taunts/props/1-61.mp3", "I'm batman!", "2", true},
	{"taunts/props/1-63.mp3", "The internet is for porn", "20", true},
	{"taunts/props/1-65.mp3", "The lion sleeps tonight", "14", false},
	{"taunts/props/1-66.mp3", "Keyboard cat", "20", false},
	{"taunts/props/1-68.mp3", "Nokia ringtone", "3", true},
	{"taunts/props/1-69.mp3", "Yeeaaahhh!", "5", false},
	{"taunts/props/1-70.mp3", "Muffin Man", "5", false},
	{"taunts/props/1-72.mp3", "Pokemon theme", "17", true},
	{"taunts/props/1-73.mp3", "Bad luck", "3", true},
	{"taunts/props/1-74.mp3", "Sexy and I know it", "9", true},
	{"taunts/props/1-75.mp3", "Spongebob Squarepants!", "28", true},
	{"taunts/props/1-76.mp3", "A-Team theme", "22", true},
	{"taunts/props/1-79.mp3", "Trolololo", "9", true},
	{"taunts/props/1-80.mp3", "Universal Studios", "24", false},
	{"taunts/props/1-81.mp3", "Pokerface", "24", true},
	{"taunts/props/1-82.mp3", "Satisfaction", "43", false},
	{"taunts/props/1-83.mp3", "Witchdoctor", "29", true},
	{"taunts/props/1-84.mp3", "Narwals", "21", true},
	{"taunts/props/1-85.mp3", "I did it", "12", false},
	{"taunts/props/1-86.mp3", "Peanut butter jelly time!", "23", true},
	{"taunts/props/1-87.mp3", "Smoke weed every day", "16", true},
	{"taunts/props/1-88a.mp3", "Goat!", "37", true},
	{"taunts/props/1-89.mp3", "What does the fox say?", "31", true},
	{"taunts/props/1-92.mp3", "I am cornholio!", "3", false},
	{"taunts/props/1-93.mp3", "My bunghole will ask", "7", true},
	{"taunts/props/1-94.mp3", "Magic!", "2", true},
	{"taunts/props/1-95.mp3", "Hey! Listen!", "2", true},
	{"taunts/props/1-96.mp3", "NyanNavi", "30", true},
	{"taunts/props/1-97.mp3", "Lana!!!", "10", true},
	{"taunts/props/1-98.mp3", "Alan!", "10", true},
	{"taunts/props/1-99.mp3", "I'm a banana!", "10", true},
	{"taunts/props/1-100.mp3", "Males use their sense of smell", "14", true},
	{"taunts/props/1-101.mp3", "Ghosting us", "10", true},
	{"taunts/props/1-102.mp3", "You're gonna have to eat it", "3", true},
	{"taunts/props/1-104.mp3", "Inanimate fucking object", "8", true},
	{"taunts/props/1-106.mp3", "Arrow in the knee", "4", false},
	{"taunts/props/1-107.mp3", "Fast food song", "28", true},
	{"taunts/props/1-108.mp3", "Flintstone running ", "2", true},
	{"taunts/props/1-109.mp3", "Surrounded by idiots", "5", true},
	{"taunts/props/1-110.mp3", "Buy one get one free", "9", false},
	{"taunts/props/1-111.mp3", "Badass over here", "2", true},
	{"taunts/props/1-112.mp3", "Wizard Harry", "4", true},
	{"taunts/props/1-113.mp3", "60% of the time", "3", false},
	{"taunts/props/1-114.mp3", "T-T-Today", "3", true},
	{"taunts/props/1-116.mp3", "Give it to me baby", "4", false},
	{"taunts/props/1-117.mp3", "My ding ding dong", "28", true},
	{"taunts/props/1-118.mp3", "America! Fuck yeah!", "3", true},
	{"taunts/props/1-120.mp3", "Do not go in there", "4", true},
	{"taunts/props/1-121.mp3", "Gatorade", "8", true},
	{"taunts/props/1-123.mp3", "Put that cookie down!", "3", true},
	{"taunts/props/1-124.mp3", "Schwing!", "2", true},
	{"taunts/props/1-125.mp3", "Barney loves you", "19", true},
	{"taunts/props/1-126.mp3", "Secret song", "26", true},
	{"taunts/props/1-127.mp3", "C is for Cookie", "26", true},
	{"taunts/props/1-128.mp3", "Teletubbies", "24", true},
	{"taunts/props/1-129.mp3", "Duck Tales", "21", true},
	{"taunts/props/1-130.mp3", "Is it me you're looking for?", "7", true},
	{"taunts/props/1-131.mp3", "Going up the stairs", "8", true},
	{"taunts/props/1-132.mp3", "Winnie the pooh", "28", true},
	{"taunts/props/1-133.mp3", "English motherfucker", "4", true},
	{"taunts/props/1-134.mp3", "Eat it!", "16", true},
	{"taunts/props/1-135.mp3", "wibwubwuwuwb", "2", true},
	{"taunts/props/1-136.mp3", "Living in the sunlight", "19", true},
	{"taunts/props/1-137.mp3", "KHAAN!", "3", true},
	{"taunts/props/1-138.mp3", "Say her name!", "7", true},
	{"taunts/props/1-139.mp3", "Yodelling", "14", true},
	{"taunts/props/1-140.mp3", "like a glove", "3", true},
	{"taunts/props/1-141.mp3", "Barbara Streisand", "16", true},
	{"taunts/props/1-142.mp3", "Erza's theme", "30", true},
	{"taunts/props/1-143.mp3", "Duracell lasts longer", "3", true},
	{"taunts/props/1-144.mp3", "B-A-N-A-N-A-S", "9", true},
	{"taunts/props/1-146.mp3", "Mario star theme", "10", true},
	{"taunts/props/1-147.mp3", "Be a man!", "21", true},
	{"taunts/props/1-148.mp3", "Pokeballin'", "12", true},
	{"taunts/props/1-149.mp3", "Sensu bean!", "2", true},
	{"taunts/props/1-150.mp3", "These aren't the droids", "3", true},
	{"taunts/props/1-151.mp3", "Your soundcard works", "3", true},
	{"taunts/props/1-152.mp3", "Giga puddin", "16", true},
	{"taunts/props/1-153.mp3", "Oh my", "6", true},
	{"taunts/props/1-154.mp3", "Say whaaat", "2", true},
	{"taunts/props/1-155.mp3", "I'm a kitty cat", "14", true},
	{"taunts/props/1-156.mp3", "Just smile and wave", "3", true},
	{"taunts/props/1-157.mp3", "Makka Pakka", "15", true},
	{"taunts/props/1-158.mp3", "Not the bees!", "6", true},
	{"taunts/props/1-159.mp3", "They killed Kenny!", "4", true},
	{"taunts/props/1-160.mp3", "Smashing!", "10", true},
	{"taunts/props/1-161.mp3", "Hi!", "14", true},
	{"taunts/props/1-162.mp3", "Booty song", "18", true},
	{"taunts/props/1-163.mp3", "Sanic", "15", true},
	{"taunts/props/1-164.mp3", "Zelda secret", "2", true},
	{"taunts/props/1-165.mp3", "Everything is awesome", "14", true},
	{"taunts/props/1-166.mp3", "Like a loser", "14", true},
	{"taunts/props/1-167.mp3", "Titanic", "28", true},
	{"taunts/props/1-168.mp3", "Oompa loompa", "15", true},
	{"taunts/props/1-169.mp3", "I love my brick!", "2", true},
	{"taunts/props/1-170.mp3", "Behind you!", "2", true},
	{"taunts/props/1-171.mp3", "They're coming in here", "5", true},
	{"taunts/props/1-172.mp3", "I've got my corner", "2", true},
	{"taunts/props/1-173.mp3", "Get the hell out", "3", true},
	{"taunts/props/1-174.mp3", "Here come the hacks!", "2", true},
	{"taunts/props/1-175.mp3", "Haaackss!", "2", true},
	{"taunts/props/1-176.mp3", "No! No!", "2", true},
	{"taunts/props/1-177.mp3", "Ruuunn!", "2", true},
	{"taunts/props/1-178.mp3", "Can't get this tune out my head", "2", true},
	{"taunts/props/1-179.mp3", "Animal sounds", "28", true},
	{"taunts/props/1-180.mp3", "All by myself", "18", true},
	{"taunts/props/1-181.mp3", "Computer says no", "2", true},
	{"taunts/props/1-182.mp3", "Buzzer", "2", true},
	{"taunts/props/1-183.mp3", "Day 1 in the Big Brother house", "4", true},
	{"taunts/props/1-184.mp3", "He's dead Jim", "2", true},
	{"taunts/props/1-185.mp3", "I demand a trial by combat", "4", true},
	{"taunts/props/1-186.mp3", "It's only game", "4", true},
	{"taunts/props/1-187.mp3", "I've got a clue", "8", true},
	{"taunts/props/1-188.mp3", "Just keep swimming", "23", true},
	{"taunts/props/1-189.mp3", "Let it go", "25", true},
	{"taunts/props/1-190.mp3", "Mario death", "3", true},
	{"taunts/props/1-191.mp3", "Howdy ho", "2", true},
	{"taunts/props/1-192.mp3", "Got a problem buddy?", "4", true},
	{"taunts/props/1-193.mp3", "Rage quit!", "4", true},
	{"taunts/props/1-194.mp3", "Unfricken touchable", "2", true},
	{"taunts/props/1-195.mp3", "X-Files theme", "8", true},
	{"taunts/props/1-196.mp3", "Build a snow man", "22", true},
	{"taunts/props/1-197.mp3", "Cha cha slide", "31", true},
	{"taunts/props/1-198.mp3", "I volunteer", "2", true},
	{"taunts/props/1-199.mp3", "hahaha", "25", true},
	{"taunts/props/1-200.mp3", "James Bond", "21", true},
	{"taunts/props/1-201.mp3", "Mr. Lonely", "10", true},
	{"taunts/props/1-202.mp3", "My name is Jeff", "3", true},
	{"taunts/props/1-203.mp3", "Party pooper", "12", true},
	{"taunts/props/1-204.mp3", "Polly", "11", true},
	{"taunts/props/1-205.mp3", "Go bananas!", "12", true},
	{"taunts/props/1-206.mp3", "Spongebob laugh", "7", true},
	{"taunts/props/1-207.mp3", "My swamp", "23", true},
	{"taunts/props/1-208.mp3", "Whatever kills me", "2", true},
	{"taunts/props/1-209.mp3", "Loud noises!", "2", true},
	{"taunts/props/1-210.mp3", "Ievan Polka", "27", true},
	{"taunts/props/1-211.mp3", "Seduce me", "6", true},
	{"taunts/props/1-212.mp3", "Designed to stick", "12", true},
	{"taunts/props/1-213.mp3", "Die for some chickens?", "5", true},
	{"taunts/props/1-214.mp3", "Swiper no swiping", "16", true},
	{"taunts/props/1-215.mp3", "What what", "13", true},
	{"taunts/props/1-216.mp3", "Filthy Animal", "6", true},
	{"taunts/props/1-217.mp3", "Ghost Busters", "20", true},
	{"taunts/props/1-218.mp3", "Hamster dance", "7", true},
	{"taunts/props/1-219.mp3", "Shoot me in the face", "30", true},
	{"taunts/props/1-220.mp3", "MLG Horns", "3", true},
	{"taunts/props/1-221.mp3", "Sodding off", "5", true},
	{"taunts/props/1-222.mp3", "Notice me!", "4", true},
	{"taunts/props/1-223.mp3", "20th Century Fox 2", "20", true},
	{"taunts/props/1-224.mp3", "Amazing horse", "6", true},
	{"taunts/props/1-225.mp3", "My giant monkey", "10", true},
	{"taunts/props/1-226.mp3", "Cantina band", "15", true},
	{"taunts/props/1-227.mp3", "Caramell dansen", "13", true},
	{"taunts/props/1-228.mp3", "Crickets", "5", true},
	{"taunts/props/1-229.mp3", "Everybody dance now", "2", true},
	{"taunts/props/1-230.mp3", "Gasp", "2", true},
	{"taunts/props/1-231.mp3", "Gentleman goat", "17", true},
	{"taunts/props/1-232.mp3", "Heal me!", "13", true},
	{"taunts/props/1-233.mp3", "Hello you", "2", true},
	{"taunts/props/1-234.mp3", "Help me, I'm poor", "2", true},
	{"taunts/props/1-235.mp3", "I am the hype!", "2", true},
	{"taunts/props/1-236.mp3", "I love cats", "30", true},
	{"taunts/props/1-237.mp3", "Shat myself", "2", true},
	{"taunts/props/1-238.mp3", "Dial-up", "5", true},
	{"taunts/props/1-239.mp3", "Kiss my posterior", "4", true},
	{"taunts/props/1-240.mp3", "Mole!", "10", true},
	{"taunts/props/1-241.mp3", "Move! (Thomas)", "9", true},
	{"taunts/props/1-242.mp3", "Ha! Ha!", "2", true},
	{"taunts/props/1-243.mp3", "Noice", "3", true},
	{"taunts/props/1-244.mp3", "FFS", "2", true},
	{"taunts/props/1-245.mp3", "Pingu", "9", true},
	{"taunts/props/1-246.mp3", "SMRT", "9", true},
	{"taunts/props/1-247.mp3", "Something came in the mail", "9", true},
	{"taunts/props/1-248.mp3", "The Count", "31", true},
	{"taunts/props/1-249.mp3", "This is Patrick", "2", true},
	{"taunts/props/1-250.mp3", "Who throws a shoe?", "8", true},
	{"taunts/props/1-251.mp3", "You are a pirate!", "12", true},
}

// If you win, one of these will be played
// Set blank to disable
VICTORY_SOUNDS = {
	"vo/announcer_success.wav",
	"vo/announcer_victory.wav",
	"vo/announcer_we_succeeded.wav"
}

for k,v in pairs(PROP_TAUNTS) do
	sound.Add( {
	name = v[2],
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 100,
	pitch = 100,
	sound = v[1]
	} )
end

for k,v in pairs(HUNTER_TAUNTS) do
	sound.Add( {
	name = v[2],
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 100,
	pitch = 100,
	sound = v[1]
	} )
end
